name: boa

# The packages we (may) depend on
dependencies:
  - base             # For built-in functions like `length`
  - containers       # For Data.Map, etc., if needed
  # For assignment 1, don't add anything else here

# The BoaInterp library
library:
  source-dirs: src
  exposed-modules:
    - BoaAST
    - BoaInterp

executable:
  main: Main.hs
  source-dirs: src

# Sample test suite
tests:
  my-test-suite:
    main: Test.hs
    source-dirs: tests
    dependencies: # not all may be relevant
      - boa
      - tasty
      - tasty-hunit
      - QuickCheck
      - tasty-quickcheck
      # You may add other LTS-14.1 packages here, if really appropriate
